
# **Titanic Survival Prediction — Exploratory Data Analysis**

In this notebook we explore the Titanic dataset to understand its structure, distributions, relationships between features, and patterns that might help predict survival.

# 1. Import Librarues

- Librería/Bibliotecas: conjunto de código preescrito, y funciones, de esta forma no se tienen que escribir de cero. Se usa la c¿palabra clave **import** y se les asigna una abreviatura para facilitar su uso.

In [20]:
# primero se imporan las librerías

import pandas as pd 
import numpy as np # Se utiliza para el análisis y manipulación de datos.
import matplotlib.pyplot as plt # Es la biblioteca principal para la visualización de datos estática.
import seaborn as sns # extensión de Matplotlib diseñada para hacer gráficos estadísticos más atractivos y sencillos. 

# Se establece un estilo
sns.set_theme(style="darkgrid") # Lo que va entre comillas se usa para adaptar la apariencia del gráfico, se puede camnbiar de acuerdo a las necesidades
plt.rcParams["figure.figsize"] = (12, 7) # Se modifica el tamño de la figura, 12pulgadas de ancho y 7 de alto
plt.rcParams["figure.dpi"] = 100 # Se comtrola la nitidez, 100 es lo estándar, pero puede mejorar a 300

%matplotlib inline 
# Comando exclusivo de Jupyter, de esta forma los gráficos se mostrarán justo debajo de la celda de código
#(al parecer el comentario de arriba debía de ir en una líneaa aparte) si no, genera un error

# 2. Cargar los datos

In [21]:
df = pd.read_csv("data/titanic.csv") # Lee el archivo csv, en la carpeta de data y lo convierte en un DataFrama: df
print(f"Dataset shape: {df.shape[0]} rows, {df.shape[1]} colums") # df.shape devuelve una tupla (filas, columnas)
# La f antes de las comillas permite insertar las variables directamente en el texto.
df.head(10) # muestra las primeras 10 filas

Dataset shape: 891 rows, 12 colums

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
5,6,0,3,"Moran, Mr. James",male,NaN,0,0,330877,8.4583,NaN,Q
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S
7,8,0,3,"Palsson, Master. Gosta Leonard",male,2.0,3,1,349909,21.0750,NaN,S
8,9,1,3,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",female,27.0,0,2,347742,11.1333,NaN,S
9,10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.0,1,0,237736,30.0708,NaN,C

**La tabla a continuación es generada con código markdown**

Sirve como nota explicativa del dataset del Titanic (qué significa cada columna)

### Column Descriptions

| Column | Description |
| :--- | :--- |
| **PassengerId** | Unique ID for each passenger |
| **Survived** | 0 = Did not survive, 1 = Survived |
| **Pclass** | Ticket class: 1 = 1st, 2 = 2nd, 3 = 3rd |
| **Name** | Passenger name |
| **Sex** | Gender |
| **Age** | Age in years |
| **SibSp** | Number of siblings/spouses aboard |
| **Parch** | Number of parents/children aboard |
| **Ticket** | Ticket number |
| **Fare** | Passenger fare |
| **Cabin** | Cabin number |
| **Embarked** | Port of embarkation: C = Cherbourg, Q = Queenstown, S = Southampton |

# 3. Dataset Overview

In [ ]:
# Dara types y columnas no nullas
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    str
 4   Sex          891 non-null    str
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    str
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    str
 11  Embarked     889 non-null    str
dtypes: float64(2), int64(5), str(5)
memory usage: 83.7 KB

In [14]:
# Resumen estadístico de columnas numéricas (calcula promedios y percentiles)
df.describe()

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
count,891.000000,891.000000,891.000000,714.000000,891.000000,891.000000,891.000000
mean,446.000000,0.383838,2.308642,29.699118,0.523008,0.381594,32.204208
std,257.353842,0.486592,0.836071,14.526497,1.102743,0.806057,49.693429
min,1.000000,0.000000,1.000000,0.420000,0.000000,0.000000,0.000000
25%,223.500000,0.000000,2.000000,20.125000,0.000000,0.000000,7.910400
50%,446.000000,0.000000,3.000000,28.000000,0.000000,0.000000,14.454200
75%,668.500000,1.000000,3.000000,38.000000,1.000000,0.000000,31.000000
max,891.000000,1.000000,3.000000,80.000000,8.000000,6.000000,512.329200

In [ ]:
# Resumen estadístico de columnas categóricas
df.describe(include="object")
# El resumen es exclusivamente para las columnas de texto(tipo **object**), ignorandi las numércias

/tmp/ipykernel_44690/2895978503.py:2: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  df.describe(include="object")

                           Name   Sex  Ticket Cabin Embarked
count                       891   891     891   204      889
unique                      891     2     681   147        3
top     Braund, Mr. Owen Harris  male  347082    G6        S
freq                          1   577       7     4      644

- **count**: Cantidad de valores que no están vaciós
- **unnique**: Número de valores distintis (ej. si hay 100 filas pero solo 3 colores, será 3).
- **top**: El valor que se repite (la moda)
- **freq**: Cuántas veces aparece else valor más frecuente

# 4. Missing Values Analysis

Se identifica, cuantifica y ordena los **datos faltantes** (nulos o *Nan*), para decidir cómo limpiarlos

In [ ]:
# Recuento y porcentaje de valores faltantes
missing = pd.DataFrame({ # Nueva tabla llamada missing
    #Número total de datos faltantes
    "Missing Count": df.isnull().sum(), #Calcula la suma total de valores nulos por columna vscíos=true(1), llenos=False(0)
    #Porcentaje de datos faltantes respecto al total de filas
    "Missing %": (df.isnull().sum()/len(df)*100).round(2) # len(df) redodendea a dos decimales
})
        # FIltra la tabla para mostrar solo las columas que tienen un dato faltante
missing = missing[missing["Missing Count"]> 0].sort_values("Missing %", ascending=False)
                                              # Ordena los resultados de mayor a menor procentaje, prioriza las columnas con más problemas de datos
print("Colums with missing values:")
missing

Colums with missing values:

          Missing Count  Missing %
Cabin               687      77.10
Age                 177      19.87
Embarked              2       0.22

#### Porqué hacer esto?
Te dice si:
- **Eliminar** una columna (si tiene >50-70% de faltantes)
- **Rellenar** los datos (usando la media, mediana o el valor más frecuente) si los faltantes son pocos
- **Ignorar** la columna está completa